apiVersion: v1
kind: Service
metadata:
  name: career-planning-service
  labels:
    app: career-planning-service
    microservice: career-planning
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30091
    protocol: TCP
    name: http
  selector:
    app: career-planning-service

