apiVersion: v1
kind: Service
metadata:
  name: progress-tracking-service
  labels:
    app: progress-tracking-service
    microservice: progress-tracking
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30092
    protocol: TCP
    name: http
  selector:
    app: progress-tracking-service

