apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management-service
    microservice: user-management
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30093
    protocol: TCP
    name: http
  selector:
    app: user-management-service

